[package]
name = "carron"
version = "0.9.2"
authors = ["n.takana <Alignof@outlook.com>"]
edition = "2021"
description = "RV32IMAC simulator"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev]
overflow-checks = false

[dependencies]
memmap = "0.7.0"
dbg_hex = "0.1.1"
clap = {version = "3.0.5", features=["cargo"]}
